bump core versions
dappnode/DAppNode_Installer pull request #102
Opened 2021-04-07 13:13 UTC by pablomendezroyo

Bump core versions to make the installer to download from latest github repos

2021-04-07 13:15 UTC, dapplion approved these changes

2021-04-07 13:16 UTC, dapplion requested changes
This is likely to affect our production script. Do not merge

2021-04-07 14:07 UTC, pablomendezroyo commented
> This is likely to affect our production script. Do not merge

Agree, this should fix the issue https://github.com/dappnode/DAppNode_Installer/pull/103

2021-07-06 08:49 UTC, pablomendezroyo commented
not longer needed

2021-07-06 08:49 UTC, closed without merging